export enum ProductPatternsEnum {
  SELECT_ALL_PRODUCT = 'SELECT_ALL_PRODUCT',
  SELECT_ONE_PRODUCT = 'SELECT_ONE_PRODUCT',
  CREATE_ONE_PRODUCT = 'CREATE_ONE_PRODUCT',
  UPDATE_ONE_PRODUCT = 'UPDATE_ONE_PRODUCT',
}
